services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: maniekapp
      POSTGRES_PASSWORD: maniekapp123
      POSTGRES_DB: maniek_data_base
    ports:
      - "5432:5432"